//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMANA.IFP.Data.Elba {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA/_impl/FIDUCIAGAD", ConfigurationName="Elba.BilanzdatenELBAPortType")]
    public interface BilanzdatenELBAPortType {
        
        // CODEGEN: Generating message contract since the operation uebernehmeElbaDaten is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ifpev-schema.de/BilanzdatenELBA/uebernehmeElbaDaten", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMANA.IFP.Data.Elba.uebernehmeElbaDatenResponse uebernehmeElbaDaten(AMANA.IFP.Data.Elba.uebernehmeElbaDatenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ifpev-schema.de/BilanzdatenELBA/uebernehmeElbaDaten", ReplyAction="*")]
        System.Threading.Tasks.Task<AMANA.IFP.Data.Elba.uebernehmeElbaDatenResponse> uebernehmeElbaDatenAsync(AMANA.IFP.Data.Elba.uebernehmeElbaDatenRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ifpev.de/Protocol")]
    public partial class ns1ChannelHeaderTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string versionField;
        
        private string softwareProducerField;
        
        private string idSoftwareProducerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string softwareProducer {
            get {
                return this.softwareProducerField;
            }
            set {
                this.softwareProducerField = value;
                this.RaisePropertyChanged("softwareProducer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string idSoftwareProducer {
            get {
                return this.idSoftwareProducerField;
            }
            set {
                this.idSoftwareProducerField = value;
                this.RaisePropertyChanged("idSoftwareProducer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ifpev.de/Protocol")]
    public partial class ns1TicketHeaderTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ifpev.de/Protocol")]
    public partial class ns1TargetHeaderTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ns1TargetHeaderTypInstitute instituteField;
        
        private string providerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ns1TargetHeaderTypInstitute institute {
            get {
                return this.instituteField;
            }
            set {
                this.instituteField = value;
                this.RaisePropertyChanged("institute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
                this.RaisePropertyChanged("provider");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifpev.de/Protocol")]
    public partial class ns1TargetHeaderTypInstitute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string clientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("client");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ifpev.de/Protocol")]
    public partial class ns1SessionHeaderTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string yourIdField;
        
        private string myIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string yourId {
            get {
                return this.yourIdField;
            }
            set {
                this.yourIdField = value;
                this.RaisePropertyChanged("yourId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string myId {
            get {
                return this.myIdField;
            }
            set {
                this.myIdField = value;
                this.RaisePropertyChanged("myId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ifpev.de/Protocol")]
    public partial class ns1ServiceHeaderTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string versionField;
        
        private string methodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
                this.RaisePropertyChanged("method");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ifpev.de/Protocol")]
    public partial class ns1ProtocolHeaderTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string engineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string engine {
            get {
                return this.engineField;
            }
            set {
                this.engineField = value;
                this.RaisePropertyChanged("engine");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ifpev.de/Protocol")]
    public partial class ns1IdentityHeaderTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string useridField;
        
        private ns1IdentityHeaderTypInstitute instituteField;
        
        private string providerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
                this.RaisePropertyChanged("userid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ns1IdentityHeaderTypInstitute institute {
            get {
                return this.instituteField;
            }
            set {
                this.instituteField = value;
                this.RaisePropertyChanged("institute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
                this.RaisePropertyChanged("provider");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifpev.de/Protocol")]
    public partial class ns1IdentityHeaderTypInstitute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTypeField;
        
        private string idField;
        
        private string clientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idType {
            get {
                return this.idTypeField;
            }
            set {
                this.idTypeField = value;
                this.RaisePropertyChanged("idType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("client");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns3QuittungTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool anfrageBearbeitetField;
        
        private ns3QuittungTypHinweis[] hinweiseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool AnfrageBearbeitet {
            get {
                return this.anfrageBearbeitetField;
            }
            set {
                this.anfrageBearbeitetField = value;
                this.RaisePropertyChanged("AnfrageBearbeitet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Hinweis", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ns3QuittungTypHinweis[] Hinweise {
            get {
                return this.hinweiseField;
            }
            set {
                this.hinweiseField = value;
                this.RaisePropertyChanged("Hinweise");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns3QuittungTypHinweis : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string beschreibungField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string Beschreibung {
            get {
                return this.beschreibungField;
            }
            set {
                this.beschreibungField = value;
                this.RaisePropertyChanged("Beschreibung");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns3BinaerAnhangTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typField;
        
        private string anhangIDField;
        
        private string nameField;
        
        private string beschreibungField;
        
        private byte[] dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string Typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
                this.RaisePropertyChanged("Typ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string AnhangID {
            get {
                return this.anhangIDField;
            }
            set {
                this.anhangIDField = value;
                this.RaisePropertyChanged("AnhangID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
        public string Beschreibung {
            get {
                return this.beschreibungField;
            }
            set {
                this.beschreibungField = value;
                this.RaisePropertyChanged("Beschreibung");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] Dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
                this.RaisePropertyChanged("Dokument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2XbrlAbschlussdatenTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ns2XbrlAbschlussdatenTypXBRL xBRLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ns2XbrlAbschlussdatenTypXBRL XBRL {
            get {
                return this.xBRLField;
            }
            set {
                this.xBRLField = value;
                this.RaisePropertyChanged("XBRL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2XbrlAbschlussdatenTypXBRL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2SoftwareTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string idField;
        
        private string versionField;
        
        private string herstellerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
        public string Hersteller {
            get {
                return this.herstellerField;
            }
            set {
                this.herstellerField = value;
                this.RaisePropertyChanged("Hersteller");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2AbschlussTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ns2AbschlussTypSoftware softwareField;
        
        private ns2AbschlussTypBilanz bilanzField;
        
        private string taxonomieField;
        
        private string kontenrahmenField;
        
        private string identMerkmalField;
        
        private string notizField;
        
        private ns2AbschlussTypDaten datenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ns2AbschlussTypSoftware Software {
            get {
                return this.softwareField;
            }
            set {
                this.softwareField = value;
                this.RaisePropertyChanged("Software");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ns2AbschlussTypBilanz Bilanz {
            get {
                return this.bilanzField;
            }
            set {
                this.bilanzField = value;
                this.RaisePropertyChanged("Bilanz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string Taxonomie {
            get {
                return this.taxonomieField;
            }
            set {
                this.taxonomieField = value;
                this.RaisePropertyChanged("Taxonomie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
        public string Kontenrahmen {
            get {
                return this.kontenrahmenField;
            }
            set {
                this.kontenrahmenField = value;
                this.RaisePropertyChanged("Kontenrahmen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=4)]
        public string IdentMerkmal {
            get {
                return this.identMerkmalField;
            }
            set {
                this.identMerkmalField = value;
                this.RaisePropertyChanged("IdentMerkmal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=5)]
        public string Notiz {
            get {
                return this.notizField;
            }
            set {
                this.notizField = value;
                this.RaisePropertyChanged("Notiz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public ns2AbschlussTypDaten Daten {
            get {
                return this.datenField;
            }
            set {
                this.datenField = value;
                this.RaisePropertyChanged("Daten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2AbschlussTypSoftware : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ns2SoftwareTyp versandField;
        
        private ns2SoftwareTyp erstellungField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ns2SoftwareTyp Versand {
            get {
                return this.versandField;
            }
            set {
                this.versandField = value;
                this.RaisePropertyChanged("Versand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ns2SoftwareTyp Erstellung {
            get {
                return this.erstellungField;
            }
            set {
                this.erstellungField = value;
                this.RaisePropertyChanged("Erstellung");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2AbschlussTypBilanz : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string abschlussartField;
        
        private System.DateTime abschlussstichtagField;
        
        private string bilanzierungsebeneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string Abschlussart {
            get {
                return this.abschlussartField;
            }
            set {
                this.abschlussartField = value;
                this.RaisePropertyChanged("Abschlussart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime Abschlussstichtag {
            get {
                return this.abschlussstichtagField;
            }
            set {
                this.abschlussstichtagField = value;
                this.RaisePropertyChanged("Abschlussstichtag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string Bilanzierungsebene {
            get {
                return this.bilanzierungsebeneField;
            }
            set {
                this.bilanzierungsebeneField = value;
                this.RaisePropertyChanged("Bilanzierungsebene");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2AbschlussTypDaten : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ns2XbrlAbschlussdatenTyp xbrlAbschlussdatenField;
        
        private ns3BinaerAnhangTyp[] anhaengeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ns2XbrlAbschlussdatenTyp XbrlAbschlussdaten {
            get {
                return this.xbrlAbschlussdatenField;
            }
            set {
                this.xbrlAbschlussdatenField = value;
                this.RaisePropertyChanged("XbrlAbschlussdaten");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Anhaenge", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ns3BinaerAnhangTyp[] Anhaenge {
            get {
                return this.anhaengeField;
            }
            set {
                this.anhaengeField = value;
                this.RaisePropertyChanged("Anhaenge");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns4KontaktdatenTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ns4NameTyp ansprechpartnerField;
        
        private string telefonField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ns4NameTyp Ansprechpartner {
            get {
                return this.ansprechpartnerField;
            }
            set {
                this.ansprechpartnerField = value;
                this.RaisePropertyChanged("Ansprechpartner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string Telefon {
            get {
                return this.telefonField;
            }
            set {
                this.telefonField = value;
                this.RaisePropertyChanged("Telefon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns4NameTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string anredeField;
        
        private string vornameField;
        
        private string nachnameField;
        
        private string namenserweiterungField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string Anrede {
            get {
                return this.anredeField;
            }
            set {
                this.anredeField = value;
                this.RaisePropertyChanged("Anrede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string Vorname {
            get {
                return this.vornameField;
            }
            set {
                this.vornameField = value;
                this.RaisePropertyChanged("Vorname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string Nachname {
            get {
                return this.nachnameField;
            }
            set {
                this.nachnameField = value;
                this.RaisePropertyChanged("Nachname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
        public string Namenserweiterung {
            get {
                return this.namenserweiterungField;
            }
            set {
                this.namenserweiterungField = value;
                this.RaisePropertyChanged("Namenserweiterung");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns3BankIDTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string artField;
        
        private string wertField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string Art {
            get {
                return this.artField;
            }
            set {
                this.artField = value;
                this.RaisePropertyChanged("Art");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string Wert {
            get {
                return this.wertField;
            }
            set {
                this.wertField = value;
                this.RaisePropertyChanged("Wert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2EmpfaengerTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ns3BankIDTyp bankIDField;
        
        private ns4AdresseTyp anschriftField;
        
        private ns4NameTyp ansprechpartnerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ns3BankIDTyp BankID {
            get {
                return this.bankIDField;
            }
            set {
                this.bankIDField = value;
                this.RaisePropertyChanged("BankID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ns4AdresseTyp Anschrift {
            get {
                return this.anschriftField;
            }
            set {
                this.anschriftField = value;
                this.RaisePropertyChanged("Anschrift");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ns4NameTyp Ansprechpartner {
            get {
                return this.ansprechpartnerField;
            }
            set {
                this.ansprechpartnerField = value;
                this.RaisePropertyChanged("Ansprechpartner");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns4AdresseTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ns4HausanschriftTyp hausanschriftField;
        
        private ns4PostfachTyp postfachField;
        
        private string landField;
        
        private string bundeslandField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ns4HausanschriftTyp Hausanschrift {
            get {
                return this.hausanschriftField;
            }
            set {
                this.hausanschriftField = value;
                this.RaisePropertyChanged("Hausanschrift");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ns4PostfachTyp Postfach {
            get {
                return this.postfachField;
            }
            set {
                this.postfachField = value;
                this.RaisePropertyChanged("Postfach");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string Land {
            get {
                return this.landField;
            }
            set {
                this.landField = value;
                this.RaisePropertyChanged("Land");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
        public string Bundesland {
            get {
                return this.bundeslandField;
            }
            set {
                this.bundeslandField = value;
                this.RaisePropertyChanged("Bundesland");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns4HausanschriftTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strasse_HausnummerField;
        
        private string pLZField;
        
        private string ortField;
        
        private string teilortField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string Strasse_Hausnummer {
            get {
                return this.strasse_HausnummerField;
            }
            set {
                this.strasse_HausnummerField = value;
                this.RaisePropertyChanged("Strasse_Hausnummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string PLZ {
            get {
                return this.pLZField;
            }
            set {
                this.pLZField = value;
                this.RaisePropertyChanged("PLZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string Ort {
            get {
                return this.ortField;
            }
            set {
                this.ortField = value;
                this.RaisePropertyChanged("Ort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
        public string Teilort {
            get {
                return this.teilortField;
            }
            set {
                this.teilortField = value;
                this.RaisePropertyChanged("Teilort");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns4PostfachTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pLZField;
        
        private string ortField;
        
        private string nummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string PLZ {
            get {
                return this.pLZField;
            }
            set {
                this.pLZField = value;
                this.RaisePropertyChanged("PLZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string Ort {
            get {
                return this.ortField;
            }
            set {
                this.ortField = value;
                this.RaisePropertyChanged("Ort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string Nummer {
            get {
                return this.nummerField;
            }
            set {
                this.nummerField = value;
                this.RaisePropertyChanged("Nummer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2KontaktdatenAbsenderTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ns4NameTyp ansprechpartnerField;
        
        private string telefonField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ns4NameTyp Ansprechpartner {
            get {
                return this.ansprechpartnerField;
            }
            set {
                this.ansprechpartnerField = value;
                this.RaisePropertyChanged("Ansprechpartner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string Telefon {
            get {
                return this.telefonField;
            }
            set {
                this.telefonField = value;
                this.RaisePropertyChanged("Telefon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns4NameEinfachTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string namenszusatzField;
        
        private string namensergaenzungField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string Namenszusatz {
            get {
                return this.namenszusatzField;
            }
            set {
                this.namenszusatzField = value;
                this.RaisePropertyChanged("Namenszusatz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string Namensergaenzung {
            get {
                return this.namensergaenzungField;
            }
            set {
                this.namensergaenzungField = value;
                this.RaisePropertyChanged("Namensergaenzung");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2KanzleiTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ns2IdentifikationSteuerberaterTypIdentifikation[] identifikationenField;
        
        private ns4AdresseTyp adresseField;
        
        private ns4NameEinfachTyp nameAbsenderField;
        
        private ns2KontaktdatenAbsenderTyp kontaktdatenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Identifikation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ns2IdentifikationSteuerberaterTypIdentifikation[] Identifikationen {
            get {
                return this.identifikationenField;
            }
            set {
                this.identifikationenField = value;
                this.RaisePropertyChanged("Identifikationen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ns4AdresseTyp Adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
                this.RaisePropertyChanged("Adresse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ns4NameEinfachTyp NameAbsender {
            get {
                return this.nameAbsenderField;
            }
            set {
                this.nameAbsenderField = value;
                this.RaisePropertyChanged("NameAbsender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ns2KontaktdatenAbsenderTyp Kontaktdaten {
            get {
                return this.kontaktdatenField;
            }
            set {
                this.kontaktdatenField = value;
                this.RaisePropertyChanged("Kontaktdaten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2IdentifikationSteuerberaterTypIdentifikation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string artField;
        
        private string wertField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string Art {
            get {
                return this.artField;
            }
            set {
                this.artField = value;
                this.RaisePropertyChanged("Art");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string Wert {
            get {
                return this.wertField;
            }
            set {
                this.wertField = value;
                this.RaisePropertyChanged("Wert");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2BilanzdatenTyp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ns2KanzleiTyp absenderField;
        
        private ns2EmpfaengerTyp empfaengerField;
        
        private ns2BilanzdatenTypKunde kundeField;
        
        private ns2AbschlussTyp[] abschlussField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ns2KanzleiTyp Absender {
            get {
                return this.absenderField;
            }
            set {
                this.absenderField = value;
                this.RaisePropertyChanged("Absender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ns2EmpfaengerTyp Empfaenger {
            get {
                return this.empfaengerField;
            }
            set {
                this.empfaengerField = value;
                this.RaisePropertyChanged("Empfaenger");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ns2BilanzdatenTypKunde Kunde {
            get {
                return this.kundeField;
            }
            set {
                this.kundeField = value;
                this.RaisePropertyChanged("Kunde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Abschluss", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ns2AbschlussTyp[] Abschluss {
            get {
                return this.abschlussField;
            }
            set {
                this.abschlussField = value;
                this.RaisePropertyChanged("Abschluss");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2BilanzdatenTypKunde : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ns2IdentifikationKundeTypIdentifikation[] identifikationenField;
        
        private string nameField;
        
        private ns4AdresseTyp adresseField;
        
        private ns4KontaktdatenTyp kontaktdatenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Identifikation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ns2IdentifikationKundeTypIdentifikation[] Identifikationen {
            get {
                return this.identifikationenField;
            }
            set {
                this.identifikationenField = value;
                this.RaisePropertyChanged("Identifikationen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ns4AdresseTyp Adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
                this.RaisePropertyChanged("Adresse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ns4KontaktdatenTyp Kontaktdaten {
            get {
                return this.kontaktdatenField;
            }
            set {
                this.kontaktdatenField = value;
                this.RaisePropertyChanged("Kontaktdaten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ifpev-schema.de/BilanzdatenELBA")]
    public partial class ns2IdentifikationKundeTypIdentifikation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string artField;
        
        private string wertField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string Art {
            get {
                return this.artField;
            }
            set {
                this.artField = value;
                this.RaisePropertyChanged("Art");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string Wert {
            get {
                return this.wertField;
            }
            set {
                this.wertField = value;
                this.RaisePropertyChanged("Wert");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uebernehmeElbaDatenRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ifpev.de/Protocol")]
        public AMANA.IFP.Data.Elba.ns1ChannelHeaderTyp Channel;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ifpev.de/Protocol")]
        public AMANA.IFP.Data.Elba.ns1IdentityHeaderTyp Identity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ifpev.de/Protocol")]
        public AMANA.IFP.Data.Elba.ns1ProtocolHeaderTyp Protocol;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ifpev.de/Protocol")]
        public AMANA.IFP.Data.Elba.ns1ServiceHeaderTyp Service;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ifpev.de/Protocol")]
        public AMANA.IFP.Data.Elba.ns1SessionHeaderTyp Session;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ifpev.de/Protocol")]
        public AMANA.IFP.Data.Elba.ns1TargetHeaderTyp Target;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ifpev.de/Protocol")]
        public AMANA.IFP.Data.Elba.ns1TicketHeaderTyp Ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA", Order=0)]
        public AMANA.IFP.Data.Elba.ns2BilanzdatenTyp uebernehmeElbaDaten;
        
        public uebernehmeElbaDatenRequest() {
        }
        
        public uebernehmeElbaDatenRequest(AMANA.IFP.Data.Elba.ns1ChannelHeaderTyp Channel, AMANA.IFP.Data.Elba.ns1IdentityHeaderTyp Identity, AMANA.IFP.Data.Elba.ns1ProtocolHeaderTyp Protocol, AMANA.IFP.Data.Elba.ns1ServiceHeaderTyp Service, AMANA.IFP.Data.Elba.ns1SessionHeaderTyp Session, AMANA.IFP.Data.Elba.ns1TargetHeaderTyp Target, AMANA.IFP.Data.Elba.ns1TicketHeaderTyp Ticket, AMANA.IFP.Data.Elba.ns2BilanzdatenTyp uebernehmeElbaDaten) {
            this.Channel = Channel;
            this.Identity = Identity;
            this.Protocol = Protocol;
            this.Service = Service;
            this.Session = Session;
            this.Target = Target;
            this.Ticket = Ticket;
            this.uebernehmeElbaDaten = uebernehmeElbaDaten;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uebernehmeElbaDatenResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ifpev.de/Protocol")]
        public AMANA.IFP.Data.Elba.ns1ProtocolHeaderTyp Protocol;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ifpev.de/Protocol")]
        public AMANA.IFP.Data.Elba.ns1SessionHeaderTyp Session;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ifpev.de/Protocol")]
        public AMANA.IFP.Data.Elba.ns1TargetHeaderTyp Target;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ifpev.de/Protocol")]
        public AMANA.IFP.Data.Elba.ns1TicketHeaderTyp Ticket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ifpev-schema.de/BilanzdatenELBA", Order=0)]
        public AMANA.IFP.Data.Elba.ns3QuittungTyp Rueckmeldung;
        
        public uebernehmeElbaDatenResponse() {
        }
        
        public uebernehmeElbaDatenResponse(AMANA.IFP.Data.Elba.ns1ProtocolHeaderTyp Protocol, AMANA.IFP.Data.Elba.ns1SessionHeaderTyp Session, AMANA.IFP.Data.Elba.ns1TargetHeaderTyp Target, AMANA.IFP.Data.Elba.ns1TicketHeaderTyp Ticket, AMANA.IFP.Data.Elba.ns3QuittungTyp Rueckmeldung) {
            this.Protocol = Protocol;
            this.Session = Session;
            this.Target = Target;
            this.Ticket = Ticket;
            this.Rueckmeldung = Rueckmeldung;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BilanzdatenELBAPortTypeChannel : AMANA.IFP.Data.Elba.BilanzdatenELBAPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BilanzdatenELBAPortTypeClient : System.ServiceModel.ClientBase<AMANA.IFP.Data.Elba.BilanzdatenELBAPortType>, AMANA.IFP.Data.Elba.BilanzdatenELBAPortType {
        
        public BilanzdatenELBAPortTypeClient() {
        }
        
        public BilanzdatenELBAPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BilanzdatenELBAPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BilanzdatenELBAPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BilanzdatenELBAPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMANA.IFP.Data.Elba.uebernehmeElbaDatenResponse AMANA.IFP.Data.Elba.BilanzdatenELBAPortType.uebernehmeElbaDaten(AMANA.IFP.Data.Elba.uebernehmeElbaDatenRequest request) {
            return base.Channel.uebernehmeElbaDaten(request);
        }
        
        public AMANA.IFP.Data.Elba.ns3QuittungTyp uebernehmeElbaDaten(AMANA.IFP.Data.Elba.ns1ChannelHeaderTyp Channel, AMANA.IFP.Data.Elba.ns1IdentityHeaderTyp Identity, ref AMANA.IFP.Data.Elba.ns1ProtocolHeaderTyp Protocol, AMANA.IFP.Data.Elba.ns1ServiceHeaderTyp Service, ref AMANA.IFP.Data.Elba.ns1SessionHeaderTyp Session, ref AMANA.IFP.Data.Elba.ns1TargetHeaderTyp Target, ref AMANA.IFP.Data.Elba.ns1TicketHeaderTyp Ticket, AMANA.IFP.Data.Elba.ns2BilanzdatenTyp uebernehmeElbaDaten1) {
            AMANA.IFP.Data.Elba.uebernehmeElbaDatenRequest inValue = new AMANA.IFP.Data.Elba.uebernehmeElbaDatenRequest();
            inValue.Channel = Channel;
            inValue.Identity = Identity;
            inValue.Protocol = Protocol;
            inValue.Service = Service;
            inValue.Session = Session;
            inValue.Target = Target;
            inValue.Ticket = Ticket;
            inValue.uebernehmeElbaDaten = uebernehmeElbaDaten1;
            AMANA.IFP.Data.Elba.uebernehmeElbaDatenResponse retVal = ((AMANA.IFP.Data.Elba.BilanzdatenELBAPortType)(this)).uebernehmeElbaDaten(inValue);
            Protocol = retVal.Protocol;
            Session = retVal.Session;
            Target = retVal.Target;
            Ticket = retVal.Ticket;
            return retVal.Rueckmeldung;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AMANA.IFP.Data.Elba.uebernehmeElbaDatenResponse> AMANA.IFP.Data.Elba.BilanzdatenELBAPortType.uebernehmeElbaDatenAsync(AMANA.IFP.Data.Elba.uebernehmeElbaDatenRequest request) {
            return base.Channel.uebernehmeElbaDatenAsync(request);
        }
        
        public System.Threading.Tasks.Task<AMANA.IFP.Data.Elba.uebernehmeElbaDatenResponse> uebernehmeElbaDatenAsync(AMANA.IFP.Data.Elba.ns1ChannelHeaderTyp Channel, AMANA.IFP.Data.Elba.ns1IdentityHeaderTyp Identity, AMANA.IFP.Data.Elba.ns1ProtocolHeaderTyp Protocol, AMANA.IFP.Data.Elba.ns1ServiceHeaderTyp Service, AMANA.IFP.Data.Elba.ns1SessionHeaderTyp Session, AMANA.IFP.Data.Elba.ns1TargetHeaderTyp Target, AMANA.IFP.Data.Elba.ns1TicketHeaderTyp Ticket, AMANA.IFP.Data.Elba.ns2BilanzdatenTyp uebernehmeElbaDaten) {
            AMANA.IFP.Data.Elba.uebernehmeElbaDatenRequest inValue = new AMANA.IFP.Data.Elba.uebernehmeElbaDatenRequest();
            inValue.Channel = Channel;
            inValue.Identity = Identity;
            inValue.Protocol = Protocol;
            inValue.Service = Service;
            inValue.Session = Session;
            inValue.Target = Target;
            inValue.Ticket = Ticket;
            inValue.uebernehmeElbaDaten = uebernehmeElbaDaten;
            return ((AMANA.IFP.Data.Elba.BilanzdatenELBAPortType)(this)).uebernehmeElbaDatenAsync(inValue);
        }
    }
}
