//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ifp.de/namespace/mappings")]
[System.Xml.Serialization.XmlRootAttribute("Umgebung", Namespace="http://www.ifp.de/namespace/mappings", IsNullable=false)]
public enum UmgebungType {
    
    /// <remarks/>
    test,
    
    /// <remarks/>
    prod,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifp.de/namespace/mappings")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifp.de/namespace/mappings", IsNullable=false)]
public partial class Mapping {
    
    private UmgebungType umgebungField;
    
    private string gueltig_abField;
    
    private string gueltig_bisField;
    
    private string bLZField;
    
    private string bICField;
    
    private Kontakt kontaktField;
    
    private string iFPIDField;
    
    private Version[] versionField;
    
    private System.DateTime dateField;
    
    /// <remarks/>
    public UmgebungType Umgebung {
        get {
            return this.umgebungField;
        }
        set {
            this.umgebungField = value;
        }
    }
    
    /// <remarks/>
    public string Gueltig_ab {
        get {
            return this.gueltig_abField;
        }
        set {
            this.gueltig_abField = value;
        }
    }
    
    /// <remarks/>
    public string Gueltig_bis {
        get {
            return this.gueltig_bisField;
        }
        set {
            this.gueltig_bisField = value;
        }
    }
    
    /// <remarks/>
    public string BLZ {
        get {
            return this.bLZField;
        }
        set {
            this.bLZField = value;
        }
    }
    
    /// <remarks/>
    public string BIC {
        get {
            return this.bICField;
        }
        set {
            this.bICField = value;
        }
    }
    
    /// <remarks/>
    public Kontakt Kontakt {
        get {
            return this.kontaktField;
        }
        set {
            this.kontaktField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IFP-ID")]
    public string IFPID {
        get {
            return this.iFPIDField;
        }
        set {
            this.iFPIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Version")]
    public Version[] Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifp.de/namespace/mappings")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifp.de/namespace/mappings", IsNullable=false)]
public partial class Kontakt {
    
    private string mailField;
    
    private string telefonField;
    
    /// <remarks/>
    public string Mail {
        get {
            return this.mailField;
        }
        set {
            this.mailField = value;
        }
    }
    
    /// <remarks/>
    public string Telefon {
        get {
            return this.telefonField;
        }
        set {
            this.telefonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifp.de/namespace/mappings")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifp.de/namespace/mappings", IsNullable=false)]
public partial class Version {
    
    private string uRLField;
    
    private Taxonomie[] taxonomieField;
    
    private string verarbeitungsartField;
    
    private string nameField;
    
    /// <remarks/>
    public string URL {
        get {
            return this.uRLField;
        }
        set {
            this.uRLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Taxonomie")]
    public Taxonomie[] Taxonomie {
        get {
            return this.taxonomieField;
        }
        set {
            this.taxonomieField = value;
        }
    }
    
    /// <remarks/>
    public string Verarbeitungsart {
        get {
            return this.verarbeitungsartField;
        }
        set {
            this.verarbeitungsartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifp.de/namespace/mappings")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifp.de/namespace/mappings", IsNullable=false)]
public partial class Taxonomie {
    
    private string gueltig_abField;
    
    private string gueltig_bisField;
    
    private string nameField;
    
    /// <remarks/>
    public string Gueltig_ab {
        get {
            return this.gueltig_abField;
        }
        set {
            this.gueltig_abField = value;
        }
    }
    
    /// <remarks/>
    public string Gueltig_bis {
        get {
            return this.gueltig_bisField;
        }
        set {
            this.gueltig_bisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifp.de/namespace/mappings")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifp.de/namespace/mappings", IsNullable=false)]
public partial class Mappings {
    
    private Mapping[] mappingField;
    
    private System.DateTime dateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mapping")]
    public Mapping[] Mapping {
        get {
            return this.mappingField;
        }
        set {
            this.mappingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
}
